//
//  CountriesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import UIKit

public struct CountriesResponse: Codable {
    
    public var code: Int?
    public var message: String?
    public var payload: [Country]?

    public init(code: Int?, payload: [Country]?, message: String?) {
        self.code = code
        self.payload = payload
        self.message = message
    }

    public enum CodingKeys: String, CodingKey {
        case code
        case message
        case payload = "result"
    }
}
