//
//  State.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import UIKit

public struct State: Codable {
    
    public var code: String?
    public var name: String?

    public init(code: String?, name: String?) {
        self.code = code
        self.name = name
    }

    public enum CodingKeys: String, CodingKey {
        case code
        case name
    }
}
