//
// CountriesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class CountriesAPI {
    /**
     Get Countries
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func countriesGet(completion: @escaping ((_ data: CountriesResponse?,_ error: Error?) -> Void)) {
        countriesGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get Countries
     - GET /countries
     - Countries settings and parameters
     - API Key:
       - type: apiKey x-api-key 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "result" : true,
  "payload" : "{}",
  "message" : "message"
}}]

     - returns: RequestBuilder<CountriesResponse>
     */
    open class func countriesGetWithRequestBuilder() -> RequestBuilder<CountriesResponse> {
        let path = "/countries"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<CountriesResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
